"""Added more indexes on JobApplication

Revision ID: 10a649c2f9ee
Revises: 5b4b14965bc5
Create Date: 2026-05-19 10:15:35.741648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10a649c2f9ee'
down_revision: Union[str, Sequence[str], None] = '5b4b14965bc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_job_application_company_name'), 'job_application', ['company_name'], unique=False)
    op.create_index(op.f('ix_job_application_updated_at'), 'job_application', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_application_updated_at'), table_name='job_application')
    op.drop_index(op.f('ix_job_application_company_name'), table_name='job_application')
    # ### end Alembic commands ###
