"""Create SnoozeJobTask table

Revision ID: 10ddedd9e8b0
Revises: 6ae5da85d3ae
Create Date: 2026-04-27 12:23:57.888875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10ddedd9e8b0'
down_revision: Union[str, Sequence[str], None] = '6ae5da85d3ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snoozed_job_task',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('snoozed_count', sa.Integer(), nullable=True),
    sa.Column('next_due_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['job_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snoozed_job_task_id'), 'snoozed_job_task', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snoozed_job_task_id'), table_name='snoozed_job_task')
    op.drop_table('snoozed_job_task')
    # ### end Alembic commands ###
