"""Company and Relationship_type columns added to Contacts table

Revision ID: 1aa4092d2cea
Revises: 31e754dc73d6
Create Date: 2026-04-30 10:42:37.596680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aa4092d2cea'
down_revision: Union[str, Sequence[str], None] = '31e754dc73d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('company', sa.String(length=50), nullable=True))
    op.add_column('contacts', sa.Column('relationship_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'relationship_type')
    op.drop_column('contacts', 'company')
    # ### end Alembic commands ###
