"""Updated Documents table

Revision ID: 2fd25dab67a2
Revises: cfd095519e03
Create Date: 2026-05-11 12:19:34.800349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fd25dab67a2'
down_revision: Union[str, Sequence[str], None] = 'cfd095519e03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'file_key',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'file_key',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
