"""Altered JobApplication and Contacts table

Revision ID: 31e754dc73d6
Revises: bcb2f05afca2
Create Date: 2026-04-28 20:23:03.287019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31e754dc73d6'
down_revision: Union[str, Sequence[str], None] = 'bcb2f05afca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('job_application_id', sa.UUID(), nullable=True),
    sa.Column('contacts_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['contacts_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['job_application_id'], ['job_application.id'], )
    )
    op.drop_constraint(op.f('job_application_contacts_id_fkey'), 'job_application', type_='foreignkey')
    op.drop_column('job_application', 'contacts_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_application', sa.Column('contacts_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('job_application_contacts_id_fkey'), 'job_application', 'contacts', ['contacts_id'], ['id'], ondelete='SET NULL')
    op.drop_table('association')
    # ### end Alembic commands ###
