"""Added more indexes in Contacts, Interview and JobTask tables

Revision ID: 33ddcedb8b08
Revises: 69007a7bab36
Create Date: 2026-05-20 22:22:52.071684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33ddcedb8b08'
down_revision: Union[str, Sequence[str], None] = '69007a7bab36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_contacts_company'), 'contacts', ['company'], unique=False)
    op.create_index('ix_contacts_company_trgm', 'contacts', ['company'], unique=False, postgresql_using='gin', postgresql_ops={'company': 'gin_trgm_ops'})
    op.create_index(op.f('ix_contacts_created_at'), 'contacts', ['created_at'], unique=False)
    op.create_index(op.f('ix_contacts_name'), 'contacts', ['name'], unique=False)
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_documents_is_archived'), 'documents', ['is_archived'], unique=False)
    op.create_index(op.f('ix_documents_purpose'), 'documents', ['purpose'], unique=False)
    op.create_index(op.f('ix_interview_created_at'), 'interview', ['created_at'], unique=False)
    op.create_index(op.f('ix_interview_date'), 'interview', ['date'], unique=False)
    op.create_index(op.f('ix_interview_format'), 'interview', ['format'], unique=False)
    op.create_index(op.f('ix_interview_interviewer_name'), 'interview', ['interviewer_name'], unique=False)
    op.create_index('ix_interview_interviewer_name_trgm', 'interview', ['interviewer_name'], unique=False, postgresql_using='gin', postgresql_ops={'interviewer_name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_interview_outcome'), 'interview', ['outcome'], unique=False)
    op.create_index(op.f('ix_job_task_due_date'), 'job_task', ['due_date'], unique=False)
    op.create_index(op.f('ix_job_task_is_overdue'), 'job_task', ['is_overdue'], unique=False)
    op.create_index(op.f('ix_job_task_status'), 'job_task', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_task_status'), table_name='job_task')
    op.drop_index(op.f('ix_job_task_is_overdue'), table_name='job_task')
    op.drop_index(op.f('ix_job_task_due_date'), table_name='job_task')
    op.drop_index(op.f('ix_interview_outcome'), table_name='interview')
    op.drop_index('ix_interview_interviewer_name_trgm', table_name='interview', postgresql_using='gin', postgresql_ops={'interviewer_name': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_interview_interviewer_name'), table_name='interview')
    op.drop_index(op.f('ix_interview_format'), table_name='interview')
    op.drop_index(op.f('ix_interview_date'), table_name='interview')
    op.drop_index(op.f('ix_interview_created_at'), table_name='interview')
    op.drop_index(op.f('ix_documents_purpose'), table_name='documents')
    op.drop_index(op.f('ix_documents_is_archived'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.drop_index(op.f('ix_contacts_name'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_created_at'), table_name='contacts')
    op.drop_index('ix_contacts_company_trgm', table_name='contacts', postgresql_using='gin', postgresql_ops={'company': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_contacts_company'), table_name='contacts')
    # ### end Alembic commands ###
