"""Updated Documents table

Revision ID: 55fb3e615080
Revises: f3e5f8f53f92
Create Date: 2026-05-08 15:49:44.612092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55fb3e615080'
down_revision: Union[str, Sequence[str], None] = 'f3e5f8f53f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('file_key', sa.UUID(), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=True),
    sa.Column('purpose', sa.String(length=20), nullable=True),
    sa.Column('version_name', sa.String(length=255), nullable=True),
    sa.Column('is_latest', sa.Boolean(), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('is_base', sa.Boolean(), nullable=True),
    sa.Column('is_draft', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_file_key'), 'documents', ['file_key'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_table('documents_association_table',
    sa.Column('job_application_id', sa.UUID(), nullable=True),
    sa.Column('documents_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['documents_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['job_application_id'], ['job_application.id'], )
    )
    op.drop_index(op.f('ix_document_upload_file_key'), table_name='document_upload')
    op.drop_index(op.f('ix_document_upload_id'), table_name='document_upload')
    op.drop_index(op.f('ix_document_upload_job_application_id'), table_name='document_upload')
    op.drop_table('document_upload')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_upload',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('job_application_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_key', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('purpose', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('version_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_latest', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('upload_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_archived', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_application_id'], ['job_application.id'], name=op.f('document_upload_job_application_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('document_upload_pkey'))
    )
    op.create_index(op.f('ix_document_upload_job_application_id'), 'document_upload', ['job_application_id'], unique=False)
    op.create_index(op.f('ix_document_upload_id'), 'document_upload', ['id'], unique=False)
    op.create_index(op.f('ix_document_upload_file_key'), 'document_upload', ['file_key'], unique=False)
    op.drop_table('documents_association_table')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_file_key'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
