"""Add Documents Table

Revision ID: 579fe5d9a27d
Revises: 43fbb1522299
Create Date: 2026-04-21 15:37:53.915691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '579fe5d9a27d'
down_revision: Union[str, Sequence[str], None] = '43fbb1522299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_upload',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_application_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('file_key', sa.UUID(), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=True),
    sa.Column('purpose', sa.String(length=20), nullable=True),
    sa.Column('version_name', sa.String(length=255), nullable=True),
    sa.Column('is_latest', sa.Boolean(), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_application_id'], ['job_application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_upload_file_key'), 'document_upload', ['file_key'], unique=False)
    op.create_index(op.f('ix_document_upload_id'), 'document_upload', ['id'], unique=False)
    op.create_index(op.f('ix_document_upload_job_application_id'), 'document_upload', ['job_application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_upload_job_application_id'), table_name='document_upload')
    op.drop_index(op.f('ix_document_upload_id'), table_name='document_upload')
    op.drop_index(op.f('ix_document_upload_file_key'), table_name='document_upload')
    op.drop_table('document_upload')
    # ### end Alembic commands ###
