"""Added indexes on some JobApplication columns

Revision ID: 5b4b14965bc5
Revises: 95b80bb90b38
Create Date: 2026-05-19 10:02:08.650215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b4b14965bc5'
down_revision: Union[str, Sequence[str], None] = '95b80bb90b38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_job_application_company_name_trgm', 'job_application', ['company_name'], unique=False, postgresql_using='gin', postgresql_ops={'company_name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_job_application_created_at'), 'job_application', ['created_at'], unique=False)
    op.create_index(op.f('ix_job_application_is_archived'), 'job_application', ['is_archived'], unique=False)
    op.create_index('ix_job_application_job_title_trgm', 'job_application', ['job_title'], unique=False, postgresql_using='gin', postgresql_ops={'job_title': 'gin_trgm_ops'})
    op.create_index(op.f('ix_job_application_status'), 'job_application', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_application_status'), table_name='job_application')
    op.drop_index('ix_job_application_job_title_trgm', table_name='job_application', postgresql_using='gin', postgresql_ops={'job_title': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_job_application_is_archived'), table_name='job_application')
    op.drop_index(op.f('ix_job_application_created_at'), table_name='job_application')
    op.drop_index('ix_job_application_company_name_trgm', table_name='job_application', postgresql_using='gin', postgresql_ops={'company_name': 'gin_trgm_ops'})
    # ### end Alembic commands ###
