"""Create NotificationToken table

Revision ID: 5e75857b4006
Revises: df3059b85159
Create Date: 2026-04-23 23:43:51.226990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e75857b4006'
down_revision: Union[str, Sequence[str], None] = 'df3059b85159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_token',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('device_type', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_token_id'), 'notification_token', ['id'], unique=False)
    op.create_index(op.f('ix_notification_token_user_id'), 'notification_token', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_token_user_id'), table_name='notification_token')
    op.drop_index(op.f('ix_notification_token_id'), table_name='notification_token')
    op.drop_table('notification_token')
    # ### end Alembic commands ###
