"""Altered JobApplication, Interview table

Revision ID: 5eeda7e2554b
Revises: 579fe5d9a27d
Create Date: 2026-04-22 21:38:35.933043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eeda7e2554b'
down_revision: Union[str, Sequence[str], None] = '579fe5d9a27d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview', sa.Column('estimated_duration', sa.String(length=50), nullable=True))
    op.add_column('interview', sa.Column('actual_duration', sa.String(length=50), nullable=True))
    op.add_column('interview', sa.Column('timezone', sa.String(length=15), nullable=True))
    op.add_column('interview', sa.Column('interviewer_name', sa.String(length=50), nullable=True))
    op.add_column('interview', sa.Column('feedback', sa.String(), nullable=True))
    op.add_column('interview', sa.Column('link', sa.String(), nullable=True))
    op.add_column('job_application', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('job_task', 'job_application_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_job_task_job_application_id'), table_name='job_task')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_job_task_job_application_id'), 'job_task', ['job_application_id'], unique=False)
    op.alter_column('job_task', 'job_application_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('job_application', 'description')
    op.drop_column('interview', 'link')
    op.drop_column('interview', 'feedback')
    op.drop_column('interview', 'interviewer_name')
    op.drop_column('interview', 'timezone')
    op.drop_column('interview', 'actual_duration')
    op.drop_column('interview', 'estimated_duration')
    # ### end Alembic commands ###
