"""Added more indexes on JobApplication

Revision ID: 69007a7bab36
Revises: 10a649c2f9ee
Create Date: 2026-05-19 10:17:07.237942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69007a7bab36'
down_revision: Union[str, Sequence[str], None] = '10a649c2f9ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_job_application_job_title'), 'job_application', ['job_title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_application_job_title'), table_name='job_application')
    # ### end Alembic commands ###
