"""Altered JobTask and JobApplicationStatusHistory

Revision ID: 6ae5da85d3ae
Revises: 5e75857b4006
Create Date: 2026-04-25 00:47:14.583265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ae5da85d3ae'
down_revision: Union[str, Sequence[str], None] = '5e75857b4006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_application_status_history', sa.Column('transition_type', sa.String(length=20), nullable=True))
    op.add_column('job_task', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('job_task', sa.Column('description', sa.String(), nullable=True))
    op.add_column('job_task', sa.Column('task_type', sa.String(length=50), nullable=True))
    op.add_column('job_task', sa.Column('created_by', sa.String(length=20), nullable=True))
    op.add_column('job_task', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('job_task', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(op.f('job_task_job_application_id_fkey'), 'job_task', type_='foreignkey')
    op.create_foreign_key(None, 'job_task', 'job_application', ['job_application_id'], ['id'])
    op.create_foreign_key(None, 'job_task', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_task', type_='foreignkey')
    op.drop_constraint(None, 'job_task', type_='foreignkey')
    op.create_foreign_key(op.f('job_task_job_application_id_fkey'), 'job_task', 'job_application', ['job_application_id'], ['id'], ondelete='CASCADE')
    op.alter_column('job_task', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('job_task', 'updated_at')
    op.drop_column('job_task', 'created_by')
    op.drop_column('job_task', 'task_type')
    op.drop_column('job_task', 'description')
    op.drop_column('job_task', 'user_id')
    op.drop_column('job_application_status_history', 'transition_type')
    # ### end Alembic commands ###
