"""Updated Documents table

Revision ID: 95b80bb90b38
Revises: 2fd25dab67a2
Create Date: 2026-05-11 15:41:08.331823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95b80bb90b38'
down_revision: Union[str, Sequence[str], None] = '2fd25dab67a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('is_submitted', sa.Boolean(), nullable=True))
    op.drop_column('documents', 'is_latest')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('is_latest', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('documents', 'is_submitted')
    # ### end Alembic commands ###
