"""Modify Job Application Table

Revision ID: aad049baf839
Revises: ce5510f83881
Create Date: 2026-04-20 14:01:11.004519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aad049baf839'
down_revision: Union[str, Sequence[str], None] = 'ce5510f83881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('job_application_contacts_id_fkey'), 'job_application', type_='foreignkey')
    op.create_foreign_key(None, 'job_application', 'contacts', ['contacts_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_application', type_='foreignkey')
    op.create_foreign_key(op.f('job_application_contacts_id_fkey'), 'job_application', 'contacts', ['contacts_id'], ['id'])
    # ### end Alembic commands ###
