"""Added status and error columns to Document table

Revision ID: cfd095519e03
Revises: 55fb3e615080
Create Date: 2026-05-11 12:13:05.834402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfd095519e03'
down_revision: Union[str, Sequence[str], None] = '55fb3e615080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('documents', sa.Column('error', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'error')
    op.drop_column('documents', 'status')
    # ### end Alembic commands ###
