"""Add EmailVerificationOTP table

Revision ID: d6467c8b13f9
Revises: b51ea97e5f50
Create Date: 2026-04-13 17:23:33.616767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6467c8b13f9'
down_revision: Union[str, Sequence[str], None] = 'b51ea97e5f50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_otp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('otp', sa.String(length=6), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_expired', sa.Boolean(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_otp_email'), 'email_verification_otp', ['email'], unique=True)
    op.create_index(op.f('ix_email_verification_otp_otp'), 'email_verification_otp', ['otp'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_verification_otp_otp'), table_name='email_verification_otp')
    op.drop_index(op.f('ix_email_verification_otp_email'), table_name='email_verification_otp')
    op.drop_table('email_verification_otp')
    # ### end Alembic commands ###
