"""Remove Unique flag from email on EmailVerification

Revision ID: d9406f1c5ef4
Revises: d6467c8b13f9
Create Date: 2026-04-14 11:57:16.026807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9406f1c5ef4'
down_revision: Union[str, Sequence[str], None] = 'd6467c8b13f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_verification_otp_email'), table_name='email_verification_otp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_email_verification_otp_email'), 'email_verification_otp', ['email'], unique=True)
    # ### end Alembic commands ###
