"""Few tweaks in JobApplication, Contacts Table

Revision ID: df3059b85159
Revises: 5eeda7e2554b
Create Date: 2026-04-22 22:45:44.938624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df3059b85159'
down_revision: Union[str, Sequence[str], None] = '5eeda7e2554b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'role',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.alter_column('job_application', 'date_applied',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_application', 'date_applied',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('contacts', 'role',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    # ### end Alembic commands ###
