"""Created NoteLog table for contacts and added new columns on Contacts table

Revision ID: f3e5f8f53f92
Revises: 1aa4092d2cea
Create Date: 2026-04-30 12:24:37.656340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3e5f8f53f92'
down_revision: Union[str, Sequence[str], None] = '1aa4092d2cea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contacts_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contacts_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_log_contacts_id'), 'note_log', ['contacts_id'], unique=False)
    op.create_index(op.f('ix_note_log_id'), 'note_log', ['id'], unique=False)
    op.add_column('contacts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('contacts', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('contacts', 'updated_at')
    op.drop_index(op.f('ix_note_log_id'), table_name='note_log')
    op.drop_index(op.f('ix_note_log_contacts_id'), table_name='note_log')
    op.drop_table('note_log')
    # ### end Alembic commands ###
